- lib/src/common/utils.dart
`system32` should be `System32`
> Fixed typo in Windows dir

- docs/README.md
- docs/index.html
- docs/styles.css
* Fixed missing stylesheet
* Added padding to logo in footer - see attached screenshot.
> docs: styling update

- packages/melos/lib/src/command/version.dart
Fix the help message so that the style is more alined with other help messages.
> fix(version): re-word the help message of the --yes args in version command.

- melos.yaml
- packages/melos/lib/src/command_runner.dart
> fix: don't recreate currentWorkspace if already created (fixes #39)

- packages/melos/README.md
- packages/melos/lib/src/command/bootstrap.dart
- packages/melos/lib/src/command/list.dart
- packages/melos/lib/src/command/version.dart
- packages/melos/lib/src/command_runner.dart
- packages/melos/lib/src/common/changelog.dart
- packages/melos/lib/src/common/pending_package_update.dart
- packages/melos/lib/src/common/utils.dart
- packages/melos/lib/src/common/versioning.dart
- packages/melos/pubspec.yaml
- pubspec.yaml
This adds support for `melos version <packageName> <newVersion>`.
> feat: allow manually versioning a specific package via `melos version`

- packages/melos/README.md
- packages/melos/lib/src/command/run.dart
- packages/melos/lib/src/command/version.dart
- packages/melos/lib/src/command_runner.dart
- packages/melos/lib/src/common/utils.dart
- packages/melos/lib/src/common/workspace.dart
- packages/melos/lib/src/common/workspace_script.dart
> feat: add various new flags

- docs/commands.md
- packages/melos/lib/src/command/list.dart
Adopted from `multipack` https://github.com/gql-dart/multipack/blob/master/lib/commands/info.dart.
> feat: allow listing packages in Graphviz DOT language

- packages/melos/README.md
Added my company opensource project to docs to support the usage of melos
> chore: added package to docs

- packages/melos/lib/src/command/publish.dart
> feat: add --yes flag to `melos publish`

- .gitignore
- packages/melos/lib/src/command/bootstrap.dart
- packages/melos/lib/src/common/package.dart
- packages/melos/lib/src/common/workspace.dart
> feat: `melos bootstrap` now executes generates its temporary project inside the .dart_tool folder

- bin/melos_dev.dart
- packages/melos/bin/melos.dart
- packages/melos/lib/melos.dart
- packages/melos/lib/src/command/bootstrap.dart
- packages/melos/lib/src/command/clean.dart
- packages/melos/lib/src/command/version.dart
- packages/melos/lib/src/command_runner.dart
> refactor: remove MelosCommandRunner.instance

- packages/ansi_styles/CHANGELOG.md
- packages/ansi_styles/pubspec.yaml
- packages/conventional_commit/CHANGELOG.md
- packages/conventional_commit/pubspec.yaml
- ansi_styles@0.3.0
- conventional_commit@0.4.0
> chore(release): publish packages

- packages/melos/lib/src/common/package.dart
> refactor: set Melos as the generator for generated pub files

- packages/melos/lib/src/commands/version.dart
> chore: fix lints on master channel

- docs/commands.mdx
Just a minor typo on the docs, hope this fix sorts it.
> docs: Fixed comment on since filter

- packages/melos/lib/src/package.dart
- packages/melos/test/matchers.dart
- packages/melos/test/utils.dart
- packages/melos/test/workspace_test.dart
> feat: Added an error message when multiple packages in the workspace have the same name

- packages/melos/lib/src/commands/bootstrap.dart
> feat: use `dart` tool to run `pub get` in pure Dart package

- docs/commands.mdx
Automated Releases link is broken, so I fixed it.
Thanks for the great package.
> docs: Fixed Automated Release link.

- docs/index.mdx
- packages/melos/README.md
The order was somewhat by GitHub stars I think, is it okay to have Flame second or should I add it last? :)
> docs: add Flame to projects using Melos

- packages/melos/lib/src/command_runner/run.dart
- packages/melos/lib/src/commands/run.dart
- packages/melos/test/commands/run_test.dart
> feat: allow passing additional arguments to run commands

- packages/melos/lib/src/common/utils.dart
- packages/melos/lib/src/package.dart
> fix: Issue where symlinks are followed too deeply causing a "File name too long" exception

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
This PR adds issue forms for GitHub for bug reports and and feature requests. Additionally, a PR template has been included identical to the one being used here.
Screenshots of what these templates look like have been attached.
The "Bug Report" issue form has two labels it will automatically attach; `bug` and `triage`, both of which might not be created yet. For these to work, they need to be created by a repo maintainer, such as @Salakar.
The same goes for the "Feature Request" form, which uses the `feature request` and `triage` labels. I'm open to changing these labels to see fit! 😄
| New Issues page | Bug Report page | Feature Request page |
| --- | --- | --- |
|<img width="889" alt="image" src="https://user-images.githubusercontent.com/14292245/151434438-1e5bbe97-841c-4182-ac9c-f0ebed2 …
> docs: add bug, feature request & pr templates

- packages/melos/lib/src/commands/bootstrap.dart
> fix: fully consume `pub get` output when bootstrapping

- packages/melos/lib/src/commands/version.dart
- packages/melos/lib/src/package.dart
- packages/melos/pubspec.yaml
When we call `melos version` the package's pubspec.yaml should be updated to the latest dependency version. But, currently not works if the package is hosted in external hosted (self hosted pub).
> fix: support external hosted dependencies

- packages/melos/bin/melos.dart
- packages/melos/lib/src/command_runner.dart
- packages/melos/pubspec.yaml
fixes https://github.com/invertase/melos/issues/271.
adds autoupdater
> feat: allow checking melos version (`melos --version`) outside of workspaces & set up autoupdater

- packages/melos/lib/src/commands/bootstrap.dart
- packages/melos/lib/src/common/utils.dart
- packages/melos/test/commands/bootstrap_test.dart
- packages/melos/test/commands/exec_test.dart
- packages/melos/test/commands/list_test.dart
- packages/melos/test/commands/run_test.dart
- packages/melos/test/matchers.dart
> perf: run `pub get` in parallel during bootstrapping

- packages/melos/lib/src/common/utils.dart
- packages/melos/test/workspace_test.dart
> fix: handle unresolvable symbolic links

- docs/index.mdx
- packages/melos/README.md
> docs: added WiFiFlutter as proj using melos

- docs/commands/bootstrap.mdx
> docs: Fix spelling of postbootstrap

- packages/melos/lib/src/commands/bootstrap.dart
- packages/melos/lib/src/common/utils.dart
> feat: start to log `pub get` output if it runs for more than 10s

- packages/melos/lib/src/commands/bootstrap.dart
- packages/melos/test/commands/bootstrap_test.dart
> fix: respect user `dependency_overrides`

- packages/melos/lib/src/command_runner/script.dart
> fix: pass extra args to script when invoked without `run`

- packages/melos/bin/melos.dart
This prevents printing a stack trace for simple usage errors.
> fix: handle `UsageException`

- packages/melos/README.md
The [FlutterFire](https://github.com/firebase/flutterfire) repository moved from the FirebaseExtended to the Firebase GitHub organization.
> docs: update link to the FlutterFire repository

- docs/index.mdx
Didn't know that there is also a list of the repositories in the documentation, sorry 🫠 Follow up of #338
> docs: update link to the FlutterFire repository (part 2)

- packages/melos/test/commands/exec_test.dart
- packages/melos/test/commands/list_test.dart
- packages/melos/test/commands/run_test.dart
- packages/melos/test/mock_workspace_fs.dart
- packages/melos/test/utils.dart
> test: run all tests on Windows

- docs/configuration/overview.mdx
> docs: fix typo "comparred" in `overview.mdx`

- docs/configuration/overview.mdx
Sorry for creating a separate PR. Found that typo after opening #352.
> docs: fix typo "exluded" in `overview.mdx`

- packages/melos/pubspec.yaml
Adding the Melos homepage (https://melos.invertase.dev) to `pubspec.yamll` so that it's linked in pub.dev.
> refactor: use `homepage` and `repository` keys in `pubspec.yaml`

- bin/melos_dev.dart
- packages/melos/lib/src/commands/publish.dart
- packages/melos/lib/src/commands/run.dart
- packages/melos/lib/src/scripts.dart
- packages/melos/test/commands/bootstrap_test.dart
With the upgrade to Dart 2.18.0 the analyzer is finding a few more issues.
> refactor: fix a few analyzer issues

- packages/conventional_commit/pubspec.yaml
- packages/melos/pubspec.yaml
With this PR, the right section on pub.dev will show the View/report issues link to GitHub again, like [here](https://pub.dev/packages/android_id) (the show-logic was recently changed).
> chore: Add issue tracker link for pub.dev

- packages/melos/bin/melos.dart
- packages/melos/lib/src/commands/run.dart
- packages/melos/lib/src/commands/runner.dart
- packages/melos/lib/src/commands/version.dart
- packages/melos/lib/src/common/utils.dart
> fix: handle prompts when no terminal is attached to stdio

- .github/workflows/validate.yaml
- packages/melos/test/commands/clean_test.dart
- packages/melos/test/commands/run_test.dart
> test: fix unreported test failures on Windows

- docs/index.mdx
Added [atsign-foundation/at_app](https://github.com/atsign-foundation/at_app) to the projects using melos list.
> docs: Added at_app as a project using melos

- docs/index.mdx
- packages/melos/README.md
Add our project (flutter_html) to the list
Added our project (flutter_html) to the list of projects using Melos. Thanks for the good work!
> docs: add `flutter_html` to projects using Melos

- packages/melos/lib/src/commands/run.dart
- packages/melos/lib/src/common/utils.dart
> fix: return type of `promptChoice`

- CONTRIBUTING.md
- README.md
- packages/melos/README.md
Added `CONTRIBUTING.md` in the project.
Fixes issue #394
> docs: add `CONTRIBUTING.md`

- docs/configuration/scripts.mdx
|Old|New|
|-|-|
|https://melos.invertase.dev/#scriptsselect-package|https://melos.invertase.dev/configuration/scripts#scriptsselect-package|
> docs: Fix link select-package

- packages/melos/lib/src/package.dart
- packages/melos/test/package_test.dart
> fix: don't try to get published versions of private package

- packages/melos/bin/melos.dart
- packages/melos/lib/src/workspace_configs.dart
Closes #376
Signed-off-by: Sahil Soni <SscSPs@gmail.com>
Allow help to be run from anywhere and not just from inside a melos workspace
> feat: allow help to be shown from anywhere

- docs/index.mdx
- packages/melos/README.md
Add Converter NOW to projects that are using melos in the documentation
> docs: Add Converter NOW to projects that are using melos

- README.md
> docs: link Melos logo in README

- docs/guides/automated-releases.mdx
`commiting` -> `committing`
`taging` -> `tagging`
Fix typos in docs.
> docs: fix typos

- docs/index.mdx
Repo here: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder
> docs: `flutter_form_builder` is no longer using melos

- analysis_options.yaml
- packages/melos/lib/melos.dart
- packages/melos/lib/src/commands/version.dart
- packages/melos/lib/src/common/git.dart
- packages/melos/lib/src/common/pub_dependency_list.dart
- packages/melos/test/commands/bootstrap_test.dart
- packages/melos/test/commands/publish_test.dart
> chore: fix analyzer issues and tests for Dart 2.19.0

- .github/workflows/validate.yaml
- melos.yaml
> ci: cache Flutter SDK

- docs/commands/bootstrap.mdx
- docs/commands/clean.mdx
- docs/commands/version.mdx
- docs/configuration/scripts.mdx
- docs/guides/automated-releases.mdx
- docs/guides/migrations.mdx
- melos.yaml
- packages/melos/lib/src/commands/runner.dart
- packages/melos/lib/src/commands/version.dart
- packages/melos/lib/src/common/utils.dart
- packages/melos/lib/src/scripts.dart
- Make naming more consistent.
- Make `version` command hooks consistent with the hooks of other commands.
Fixes #321
> feat!: revise lifecycle hooks

- melos.yaml
- packages/melos/lib/src/commands/version.dart
> fix: only stage `CHANGELOG.md` when package version changes

- docs/configuration/overview.mdx
- packages/melos/lib/src/commands/version.dart
- packages/melos/lib/src/common/git.dart
- packages/melos/lib/src/workspace_configs.dart
> feat: fetch tags before versioning

- packages/melos/lib/src/workspace_configs.dart
> feat: improve error message for when no workspace can be found

- docs/commands/bootstrap.mdx
- docs/commands/clean.mdx
- docs/commands/version.mdx
- docs/configuration/scripts.mdx
- docs/guides/automated-releases.mdx
- docs/guides/migrations.mdx
- melos.yaml
- packages/melos/lib/src/commands/bootstrap.dart
- packages/melos/lib/src/commands/clean.dart
- packages/melos/lib/src/commands/run.dart
- packages/melos/lib/src/commands/runner.dart
- packages/melos/lib/src/commands/version.dart
- packages/melos/lib/src/scripts.dart
- packages/melos/lib/src/workspace_configs.dart
> feat!: move lifecycle hooks to command sections

- .github/workflows/validate.yaml
- melos.yaml
- packages/melos_flutter_deps_check/pubspec.yaml
> test: add package to ensure melos is compatible with Flutter dependencies

- .github/workflows/validate.yaml
> ci: use `cmd` again to run tests on windows

- packages/melos/README.md
Updated document and added a project.
> docs: add `mobx.dart` to projects using Melos

- analysis_options.yaml
- packages/melos/lib/src/commands/bootstrap.dart
- packages/melos/lib/src/commands/publish.dart
- packages/melos/lib/src/commands/version.dart
- packages/melos/lib/src/common/git.dart
- packages/melos/lib/src/common/git_repository.dart
- packages/melos/lib/src/common/intellij_project.dart
- packages/melos/lib/src/common/pending_package_update.dart
- packages/melos/lib/src/common/utils.dart
- packages/melos/lib/src/package.dart
- packages/melos/lib/src/scripts.dart
- packages/melos/lib/src/workspace_configs.dart
- packages/melos/test/commands/run_test.dart
- packages/melos/test/matchers.dart
- packages/melos/test/utils.dart
- packages/melos/test/workspace_config_test.dart
> refactor: clean up code style a bit

- docs/commands/list.mdx
- packages/melos/lib/src/command_runner/list.dart
- packages/melos/lib/src/commands/exec.dart
- packages/melos/lib/src/commands/list.dart
- packages/melos/lib/src/commands/publish.dart
- packages/melos/lib/src/common/utils.dart
- packages/melos/lib/src/workspace_configs.dart
- packages/melos/test/commands/publish_test.dart
Also improve ordering of packages for publishing if dependencies
have cycles.
> feat: support listing cycles in dependencies

- docs/configuration/overview.mdx
> docs: fix typos in docs

- packages/melos/test/commands/bootstrap_test.dart
> test: remove unnecessary whitespace from expectations

- docs/guides/automated-releases.mdx
> docs: fix link to "manual versioning"

- packages/melos/lib/src/commands/run.dart
- packages/melos/lib/src/common/git.dart
- packages/melos/lib/src/common/versioning.dart
- packages/melos/lib/src/package.dart
- packages/melos/lib/src/workspace.dart
> style: fix spelling of `its`

- packages/melos/lib/src/package.dart
> style: ignore `avoid_positional_boolean_parameters` for callback

- docs/index.mdx
- packages/melos/README.md
Add [NetGlade/auto_mappr](https://github.com/netglade/auto_mappr) to user of melos
> docs: Add NetGlade/auto_mappr to user of melos

- docs/configuration/overview.mdx
- docs/getting-started.mdx
- docs/guides/migrations.mdx
- packages/melos/lib/src/command_runner/version.dart
- packages/melos/lib/src/common/utils.dart
- packages/melos/lib/src/package.dart
- packages/melos/lib/src/workspace_configs.dart
> refactor: tidy up workspace name validation and fix docs

- packages/melos/lib/src/commands/list.dart
> feat: set exit code to 1 when detecting cycles in `melos list`

- packages/melos/lib/src/commands/run.dart
- packages/melos/lib/src/logging.dart
> feat: improve output for multi-line scripts

- docs/configuration/scripts.mdx
> docs: fix typo

- packages/melos/lib/src/common/intellij_project.dart
- packages/melos/test/commands/bootstrap_test.dart
- packages/melos/test/common/intellij_project_test.dart
- packages/melos/test/utils.dart
> fix: generate correct path in `modules.xml` for package at workspace root

- packages/melos/lib/src/commands/bootstrap.dart
- packages/melos/lib/src/commands/run.dart
- packages/melos/lib/src/commands/runner.dart
- packages/melos/lib/src/common/utils.dart
- packages/melos/lib/src/scripts.dart
- packages/melos/test/command_runner_test.dart
- packages/melos/test/commands/run_test.dart
- packages/melos/test/commands/script_test.dart
> fix: pass extra args to exec scripts

- docs/index.mdx
- packages/melos/README.md
- [x ] 📝 `docs` -- Documentation
> docs: growerp also use melos

- docs/index.mdx
- packages/melos/README.md
Hi amazing developers,
I'm using your wonderful package in my project [atproto.dart](https://github.com/myConsciousness/atproto.dart)! Thanks to Melos, I can manage nearly 10 packages very efficiently and publish them very safely on pub.dev.
This pull request is to add a link to atproto.dart. Please merge if you like :)
> docs: added link to `atproto.dart`

- packages/melos/lib/melos.dart
Resolves: https://github.com/invertase/melos/issues/537
> feat: Expose `Changelog` and `ManualVersionChange`

- packages/melos/lib/src/commands/bootstrap.dart
- packages/melos/lib/src/commands/list.dart
- packages/melos/lib/src/commands/publish.dart
- packages/melos/lib/src/commands/version.dart
- packages/melos/lib/src/common/utils.dart
- packages/melos/lib/src/package.dart
- packages/melos/test/commands/bootstrap_test.dart
- packages/melos/test/commands/clean_test.dart
- packages/melos/test/commands/run_test.dart
- packages/melos/test/package_test.dart
- packages/melos/test/utils.dart
- packages/melos/test/workspace_config_test.dart
- packages/melos/test/workspace_test.dart
> refactor: fix analyzer issues

- docs/index.mdx
- packages/melos/README.md
Add [`coverde`](https://github.com/mrverdant13/coverde) to the list of projects using Melos.
> docs(melos): add `coverde` to projects using Melos

- packages/melos/README.md
This just adds another project that uses melos to the list
> docs: add flutter_web_auth_2 to melos project list

- packages/melos/lib/src/commands/version.dart
This PR enables the changes in the workspace to be committed when `--no-tag-tag-version` is used, just like they are when it isn't used.
Closes #622
> fix!: Create commit when `--no-git-tag-version` is used

- melos.yaml
- packages/conventional_commit/pubspec.yaml
- packages/melos/pubspec.yaml
- pubspec.yaml
> chore: Bump all dependencies

- docs/getting-started.mdx
- docs/guides/migrations.mdx
- packages/melos/test/test_assets/add_to_app_json.json
- packages/melos/test/utils.dart
- packages/melos_flutter_deps_check/pubspec.yaml
Migration instructions from 3.x.x to 4.0.0.
> docs: 4.0.0 migration instructions

- CHANGELOG.md
- packages/melos/CHANGELOG.md
- packages/melos/lib/version.g.dart
- packages/melos/pubspec.yaml
```
Package Name   Current Version   Updated Version
melos          3.4.0             4.0.0
```
> chore(release): Publish Melos v4.0.0

- packages/melos/lib/src/commands/publish.dart
Due to a small bug in the unreleased #627 we were comparing with the oldest package version instead of the newest.
> fix: Compare with correct version when publish

- packages/melos/lib/src/command_runner/bootstrap.dart
Fix typing mistake on the help description for "bootstrap --enforce-lockfile" flag.
#600
> fix: Typo on the help description for "bootstrap --enforce-lockfile"

- docs/index.mdx
- packages/melos/README.md
Add [wolt_modal_sheet](https://github.com/woltapp/wolt_modal_sheet) to the README
> docs: Add wolt_modal_sheet to README

- docs/getting-started.mdx
Since many people stumble upon dependency conflicts due to that they have an app in the root of the workspace this PR adds a section to the docs suggesting a recommended directory structure.
> docs: Section about recommended directory structure

- CHANGELOG.md
- packages/melos/CHANGELOG.md
- packages/melos/lib/version.g.dart
- packages/melos/pubspec.yaml
> chore(release): Publish melos v4.1.0

- docs/index.mdx
- packages/melos/README.md
Let's expand the list of projects using Melos.
> docs: add more projects using melos

- CHANGELOG.md
- packages/melos/CHANGELOG.md
- packages/melos/lib/version.g.dart
- packages/melos/pubspec.yaml
> chore(release): Publish Melos v5.2.0

- docs.json
> docs: add links to side bar for new commands

- packages/melos/lib/src/common/git.dart
> fix: resolve to correct diff revisionRange

- docs/configuration/overview.mdx
- packages/melos/lib/src/common/git_repository.dart
- packages/melos/test/git_repository_test.dart
Adds support for Azure DevOps repository URLs. Probably also supports hosted Team Foundation Server, but I haven't had a chance to check if everything works. 
This will resolve #599
> feat: add support for Azure DevOps repository

- packages/melos/lib/src/commands/bootstrap.dart
- packages/melos/test/commands/bootstrap_test.dart
- packages/melos/test/utils.dart
> fix: Only enforce lockfile when it exists

- packages/melos/pubspec.yaml
This adds topics that the melos package so that it can be more easily discovered on pub.
Related: #712
Closes: #713
> chore: Add topics to pubspec.yaml

- packages/melos/README.md
Added [https://github.com/jhomlala/alice](https://github.com/jhomlala/alice) to "Who is using Melos?" section.
> feat: Added Alice to readme

- docs/filters.mdx
- melos.yaml
- Rename a section from "--categories" to "--category"
- Rename category example to "all"
> docs: fix category spelling

- docs/configuration/scripts.mdx
> docs: Update default concurrency value

- docs/index.mdx
- packages/melos/README.md
Add PowerSync to list of projects using Melos.
> docs: Add PowerSync to list of projects using Melos

- docs/commands/list.mdx
The list --all flag was removed in https://github.com/invertase/melos/pull/275, but the documentation was not updated.
> docs: remove list --all flag

- packages/melos/test/matchers.dart
This is a test to see if we can workaround the current problems with the tests.
> test: Ignore new available dependencies from output

- packages/melos/test/matchers.dart
This PR is used to debug why it doesn't properly ignore the dependency related lines in the tests on macOS.
> test: Debug ignore deps

- docs/commands/publish.mdx
> docs: remove duplicate publish docs

- docs/index.mdx
- Changed our "Projects Using Melos" link from `at_app` to `at_mono`.
We've since deprecated at_app and archived it. at_mono is a much more niche / interesting use-case (cross-repo dependency analysis and testing). The use-cases are not limited to what we are currently doing, but melos plays a massive role in enabling the capabilities of this use-case.
We wrote an explainer here: https://github.com/atsign-foundation/.github/blob/trunk/docs/at_mono.md (to be completed)
> docs: Update Atsign's project using link

- docs/index.mdx
- packages/melos/README.md
Add API Dash to list of projects using Melos.
> docs: Add API Dash to list of projects using Melos

- .github/workflows/validate.yaml
- melos.yaml
- packages/conventional_commit/pubspec.yaml
- packages/conventional_commit/test/conventional_commit_test.dart
- packages/melos/lib/src/command_configs/bootstrap.dart
- packages/melos/pubspec.yaml
- pubspec.yaml
Bumping the dependencies, `pubspec_parse` in specific, so that `environment` isn't nullable anymore.
> chore: Bump dependencies

- CHANGELOG.md
- packages/melos/CHANGELOG.md
- packages/melos/lib/version.g.dart
- packages/melos/pubspec.yaml
> chore(release): Publish Melos v6.3.0

- melos.yaml
- packages/melos/pubspec.yaml
Removes accidentally added `publish_to: none`
> chore: Remove accidental publish_to: none

- melos.yaml
- packages/melos/pubspec.yaml
Relaxes the file and platform dependencies so that they don't conflict with Flutter.
> chore: Relax flutter pinned deps

- CHANGELOG.md
- packages/melos/CHANGELOG.md
- packages/melos/lib/version.g.dart
- packages/melos/pubspec.yaml
> chore: Publish melos v7.0.0-dev.3

- packages/melos/lib/src/commands/version.dart
- packages/melos/lib/src/package.dart
- packages/melos/test/commands/version_test.dart
The version was not properly set, which should be resolved by this PR.
> fix: Version package correctly

- packages/melos/lib/src/command_runner.dart
- packages/melos/lib/src/command_runner/list.dart
- packages/melos/lib/src/commands/bootstrap.dart
- packages/melos/lib/src/commands/publish.dart
- packages/melos/lib/src/commands/run.dart
- packages/melos/lib/src/commands/version.dart
- packages/melos/lib/src/common/changelog.dart
- packages/melos/lib/src/common/git.dart
- packages/melos/lib/src/common/git_repository.dart
- packages/melos/lib/src/common/glob.dart
- packages/melos/lib/src/common/intellij_project.dart
- packages/melos/lib/src/common/io.dart
- packages/melos/lib/src/common/pending_package_update.dart
- packages/melos/lib/src/common/pub_credential.dart
- packages/melos/lib/src/common/utils.dart
- packages/melos/lib/src/common/validation.dart
- packages/melos/lib/src/package.dart
- packages/melos/lib/src/workspace_config.dart
- packages/melos/pubspec.yaml
- packages/melos/test/utils.dart
Fixes linting according to latest linting rules.
> chore: Fix linting

- .github/workflows/validate.yaml
- packages/melos/test/commands/exec_test.dart
- packages/melos/test/commands/format_test.dart
- packages/melos/test/commands/publish_test.dart
- packages/melos/test/commands/run_test.dart
- packages/melos/test/utils.dart
- packages/melos/test/utils_test.dart
- pubspec.yaml
This PR will fix the broken tests that appeared after the new Dart version.
~After we have moved to enabling user overwrites of the built-in scripts we should rename `test_real` to `test` again.~
> test: Fix broken tests after new flutter version

- packages/melos/pubspec.yaml
> chore: Bump linting package

- docs/index.mdx
- packages/melos/README.md
Had the urge to do this today while reading the docs 😂
I just added it at the end, lmk if there is another preferred ordering, e.g. ordered by the cuteness of the projects logo or something idk. 🤔
> docs: add jaspr to projects

- docs/getting-started.mdx
> docs: Update flame link (melos.yaml -> pubspec.yaml)

- docs.json
Remove the forgotten analyze entry (that gives a 404 now),
> docs: Remove analyze entry in list

- docs/index.mdx
- packages/melos/README.md
Add [starknet.dart](https://github.com/focustree/starknet.dart) in list of projects using melos.
> docs: add starknet.dart in projects list

- .github/workflows/latest_melos_release.yaml
- .github/workflows/pr_title.yaml
- .github/workflows/validate.yaml
> ci: bump actions

- packages/melos/lib/src/common/git.dart
The tags that are on origin should be the source of truth.
> fix: Tags from origin should be source of truth

- docs/index.mdx
- packages/melos/README.md
Add [flutter_chat_ui](https://github.com/flyerhq/flutter_chat_ui) to the list of projects using melos
> docs: add flutter_chat_ui

- docs/getting-started.mdx
closes https://github.com/invertase/melos/issues/541
> docs(windows): warn users regarding Git Bash usage

- .github/workflows/issue_manager.yaml
- Changed to `needs attention` to indicate the initial triage is over.
- Will also allow `stale` issue from being removed as `needs triage` label blocks its removal.
> chore: apply 'needs attention' to indicate OP has responded

- CHANGELOG.md
- packages/melos/CHANGELOG.md
- packages/melos/lib/version.g.dart
- packages/melos/pubspec.yaml
This prepares for the release of Melos v7.0.0
> chore(release): Publish Melos v7.0.0

- CHANGELOG.md
- packages/melos/CHANGELOG.md
- packages/melos/lib/version.g.dart
- packages/melos/pubspec.yaml
- melos@7.1.0
Prepares Melos v7.1.0 to be published.
> chore(release): Publish Melos v7.1.0

- docs/index.mdx
- packages/melos/README.md
Add [maplibre/flutter-maplibre-gl](https://github.com/maplibre/flutter-maplibre-gl) package to the list of projects using melos
> docs: Add maplibre package to README and index
