invertase/melos

.gitignore
CHANGELOG.md
lib/src/command/unpublished.dart
lib/src/command_runner.dart
lib/src/common/package.dart
lib/src/common/workspace.dart
lib/src/pub/pub_file_flutter_plugins.dart
pubspec.yaml

- Added a new filter for filtering published or unpublished packages: `--[no-]published`.
- Unpublished in this case means the package either does not exist on the Pub registry or the current local version of the package is not yet published to the Pub registry.
- Added a new command to pretty print currently unpublished packages: `melos unpublished`.
**Unpublished command example:**
**Published filter flag example:**

feat: published packages filter flag

---

lib/src/pub/pub_file_pubspec_lock.dart

the path is set to "." when we use a git referenece so to avoid this it's better to check the source instead of the path.
fix #14

fix: use source field in pubspec

---

packages/melos/lib/src/command/bootstrap.dart
packages/melos/lib/src/command/publish.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/common/workspace.dart

In newer installs of dart, pub is now a subcommand of dart rather than it's own executable. 
This causes several melos commands to fail if the user doesn't have the old pub command on their path, and only the new `dart pub` subcommand. I don't know everywhere you are using the old `pub` executable, but I've fixed the places that I have found, and verified it works with at least the `melos bootstrap` command in one of my workspaces.
Included is a new utility function to check if the user has the old `pub` executable available or not.

Fix for newer dart installs

---

.github/workflows/scripts/install-flutter.sh

Fixes current CI by remove deprecated GitHub action syntax.

chore: switch to new GitHub action path syntax

---

packages/melos/lib/src/command/version.dart
packages/melos/lib/src/common/workspace.dart

The version command requires a prompt which blocks it to be run on CI.
This PR adds a `yes` flag so the prompt can be skipped.
This also fixed a format issue.

feat: Add `--yes` flag to `melos version` for ci support.

---

melos.yaml
packages/melos/lib/src/command/version.dart
packages/melos/lib/src/common/pending_package_update.dart
packages/melos/lib/src/common/workspace.dart
packages/melos/lib/src/common/workspace_state.dart

Supporting package owners releasing `nullsafety` preid versions, by adding the `--preid` option to allow specifying a custom preid string.
Closes #29.
**Example**:
```sh
melos version --prerelease --preid=nullsafety --scope="*storage*"
```

feat: version `--preid` support

---

.github/workflows/pr_title.yaml
.github/workflows/validate.yaml

I was just in this area for react-native-firebase, so I looked at the actions here and thought I would reverse some entropy for you
checkout was v2 in one place, v1 in others, semantic PR title
was updated - I harmonized it with react-native-firebase version
since that was tested and working post-upgrade
Note:
- I don't have access to invertase/melos.git so couldn't make an in-repo branch, but I don't mind a fork workflow :-)
- the `.github/workflow/scripts` should really be github actions, those are general purpose "install dart", "install flutter" items, I'm surprised they are not? This one looks popular https://github.com/marketplace/actions/flutter-action

chore(ci): update github actions dependency versions

---

packages/melos/lib/src/command_runner.dart
packages/melos/lib/src/common/workspace.dart
packages/melos/lib/src/common/workspace_config.dart

Adds support for specifying default "ignore" patterns inside the "melos.yaml" configuration file.
**Example:**
```yaml
name: MyWorkspace
packages:
- packages/**
- "*"
ignore:
- "not_me*"
```
Additionally refactored  `MelosWorkspaceConfig.patterns` to not depend on Glob.

feat: add "ignore" support on "melos.yaml" configuration

---

docs/commands.md
packages/melos/lib/src/command/run.dart
packages/melos/lib/src/command_runner.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/common/workspace.dart
packages/melos/lib/src/common/workspace_script.dart

Exposes a `flutter` package filter to the CLI and yaml config.
My specific use case is running tests `flutter test`/`dart test`

feat: add `flutter` package filter

---

.github/workflows/scripts/install-tools.bat
.github/workflows/scripts/install-tools.sh
melos.yaml
packages/melos/lib/src/command/version.dart
packages/melos/lib/src/common/changelog.dart
packages/melos/lib/src/common/pending_package_update.dart
packages/melos/lib/src/common/versioning.dart
packages/melos/pubspec.yaml
packages/melos/test/melos_test.dart
pubspec.yaml

This PR extracts existing versioning behaviour to be more testable and adds tests for all previously expected behaviours.
Additionally this adds support for nullsafety prerelease versioning and generally follows the standard conventions, e.g. a package getting it's first nullsafety release should get a major version bump also.

feat: rework versioning with tests to support nullsafety prerelease versioning

---

packages/melos/lib/src/common/versioning.dart
packages/melos/test/melos_test.dart

E.g. we expect `0.1.0-dev.5` to be bumped to `0.2.0-1.0.nullsafety.0` and not `0.1.0-1.0.nullsafety.0` like the previous behavior. This matches the current behaviour of versions being bumped that are already >=1.0.0.

fix(version): non-nullsafety pre-major prerelease should also bump it's minor version

---

docs/index.md

Add project GetStream/stream-chat-flutter to the projects using Melos
You can check it out at this link https://github.com/GetStream/stream-chat-flutter

docs: Add project using Melos

---

docs/index.md

Just noticed that the 'Submit a PR' link in the documentation seems to be outdated, so I fixed it (hopefully right).

docs: Update 'Submit a PR' link

---

docs/commands.md
packages/melos/lib/src/command/version.dart
packages/melos/lib/src/common/git.dart

PR for feature request: #44 
Private packages can now be versioned by including the `--all [-a]` flag when running the `version` command.
Also added documentation for this new flag.

feat: allow private packages to be versioned

---

packages/melos/lib/src/command/base.dart
packages/melos/lib/src/command/bootstrap.dart
packages/melos/lib/src/command/clean.dart
packages/melos/lib/src/command/exec.dart
packages/melos/lib/src/command/list.dart
packages/melos/lib/src/command/publish.dart
packages/melos/lib/src/command/run.dart
packages/melos/lib/src/command/version.dart

Big thing here is line wrapping — previously the command runner was configured to wrap at a certain line length, but its commands were not.
Unlike CommandRunner, where you can easily supply a wrapping line length to its constructor, Command requires that you override a property.
I introduced a base class (MelosCommand) that does this (I think the class may come in handy for other formatting needs), and had all of the existing commands inherit from it. Works great!
Additionally, I gave a bit of styling love to the `versions` usage string. Nothing fancy, but it's more readable.
Fixes #70

refactor: Improve styling of command usage

---

packages/melos/lib/src/command/version.dart
packages/melos/pubspec.yaml

The `version` command's `--message` option can be optionally supplied to set a custom commit message when updating versions. If not provided, the previous default is used.
The option's value is treated as a template with a single template var, `{new_package_versions}`, which is replaced with the list of newly versioned packages. Additionally, escaped newlines are evaluated as proper newlines, making it easier to supply a multiline string to the option.
Example
```sh
melos version --message='chore(emergency_release): Hotfix is getting deployed now!\n\n{new_package_versions}'
```
I decided to include a template library to perform the substitution, and picked one that appears to be well-built and small — `mustache_templates`. I could've written something quick and dirty instead, but it …

feat: Support configurable commit messages in version command

---

packages/melos/lib/src/command/version.dart

I had misunderstood the option's callback as an opportunity to further parse the value, but it doesn't work that way.
We now perform newline replacement after reading from the args object.
(Sorry about that)

fix: Newline handling for version's message option

---

packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/common/workspace_config.dart

This is a collection of smaller changes in preparation for the melos.yaml command config implementation.
* Added comments throughout
* Reorganized members of `MelosWorkspaceConfig`
* Removed the version field (unused, undocumented — feels safe)
* Added `MelosWorkspaceConfig.fromYaml` constructor, for testability (I have tests in the next PR)

refactor: Clean up workspace code in preparation for command config implementation

---

melos.yaml
packages/melos/lib/src/command/base.dart
packages/melos/lib/src/command/version.dart
packages/melos/lib/src/common/workspace_command_config.dart
packages/melos/lib/src/common/workspace_config.dart
packages/melos/test/workspace_config_test.dart

`melos.yaml` can now contain a `command` section, which is a map of command-specific configuration objects. For example:
```yaml
name: my-mono-repo
packages:
- packages/**
command:
version: # Configuration for version command
message: Here's a commit message!
publish: # Configuration for publish command
tagPrefix: v
```
This makes available configurations for two commands, 'version' and 'publish', which have access to the config maps through the `MelosCommand.commandConfig` property.
`command.version.message` is the first implementation of such a config. The existence of this field in `melos.yaml` configures `melos version` to use its value as a commit message, unless overridden by the `--message` option.
I also wrote a few tests, but had to mess around with the `melos.yaml`'s test script …

feat: Add underpinnings of melos.yaml-driven command configuration (and version --message support)

---

packages/melos/lib/src/common/package.dart
packages/melos/pubspec.yaml
pubspec.yaml

All packages had `pub upgrade --major-version` run in their root directories.
The only upgrade that required code changes was in the `melos` package, because `http` moved to requiring `Uri`s instead of `String` URLs.

build: Upgrade package dependencies

---

packages/melos/README.md

A line break was inserting a space immediately after a paren.

docs: Rewrapped melos README to avoid an unfortunate space

---

packages/melos/lib/src/command/run.dart
packages/melos/lib/src/command_runner.dart
packages/melos/lib/src/common/glob.dart
packages/melos/lib/src/common/package.dart
packages/melos/lib/src/common/package_graph.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/common/workspace.dart
packages/melos/pubspec.yaml
packages/melos/test/matchers.dart
packages/melos/test/mock_fs.dart
packages/melos/test/mock_workspace_fs.dart
packages/melos/test/workspace_config_test.dart
packages/melos/test/workspace_test.dart

Quite a few additions here. I'm happy to split up into a few PRs. Alternatively, the commits are well organized and tightly focused, if you wanted to go one-by-one.
Adds two additional top-level filtering flags that expand the set of matched packages.
`--include-dependencies` takes the filtered list of packages, and expands them to include those packages' transitive dependencies (ignoring filters)
`--include-dependents` takes the filtered list of packages, and expands them to include those packages' transitive dependents (ignoring filters)
Example:
```sh
melos list --scope=some_package --with-dependencies # some_package, dep1, dep2, ...
```
In order to test the flags, the PR introduces the facility to mock a filesystem, and helpers for constructing a workspace's filesystem.
Rearranged …

feat: Add filtering flags for including dependencies and dependents

---

packages/melos/lib/src/common/intellij_project.dart
packages/melos/lib/src/common/utils.dart

Melos can be run from fairly arbitrary locations, depending on the PUB_HOSTED_URL environment variable, or if the script is being called directly.
To simplify searching for the templates that correspond to the currently running Melos, we use `Isolate.resolvePackageUri` to resolve Melos' package URI to a file, and base our template file paths on that.
Fixes #82

fix: Find templates using a resolved package URI

---

packages/melos/lib/src/common/workspace.dart

This check was failing because MelosPackage.version is a `Version` instance, and the value returned from MelosPackage.getPublishedVersions() is a `List<String>`.
I'd considered adding a test here, but it's slightly more involved because we'd need to be mocking pub responses. Doable (maybe using something like [`nock`](https://github.com/nock/nock)?) but felt like it needed its own PR.

fix: Fix --published/--no-published filters

---

packages/melos/lib/src/common/package.dart

The [`PUB_HOSTED_URL` environment variable](https://dart.dev/tools/pub/environment-variables) can be used to override the URL of the package server used by various dart tools.
I marked this as a breaking change, because it could potentially have consequences in environments where the variable was defined, but was previously relying on info pulled from pub.dev.

feat!: Use PUB_HOSTED_URL as pub.dev alternative if defined

---

packages/melos/lib/src/command/bootstrap.dart
packages/melos/lib/src/command_runner.dart
packages/melos/lib/src/common/intellij_project.dart
packages/melos/lib/src/common/package.dart
packages/melos/lib/src/common/platform.dart
packages/melos/lib/src/common/utils.dart
packages/melos/pubspec.yaml
packages/melos/test/mock_env.dart
packages/melos/test/mock_fs.dart
packages/melos/test/package_test.dart

This introduces the use of the `platform` package so that we can stub out the `Platform` for tests.
`currentPlatform` should be used in place of direct `Platform` access. It can be overridden through a Zone value, which is useful in testing scenarios (see included test for an example).
**Side note**: This is where Dart's lack of custom lints can be felt. In an ideal system, I'd want to set up a rule where direct use of `Platform` warned the user.

refactor: Move to a stubbable Platform abstraction

---

packages/melos/lib/src/common/intellij_project.dart

Make `melos bootstrap` and `melos clean` only delete `.idea/runConfigurations/melos_.xml` files.
Some projects may add custom run configurations and commit them to git.
I think it's better to only clean files created by melos.

feat: make intellij project clean only delete melos run configurations

---

packages/melos/lib/src/common/intellij_project.dart

Sorry for the mistake in #96 that creates an incorrect glob pattern in windows.
Glob always uses the `/` as the separator (https://pub.dev/packages/glob#syntax).

fix: incorrect intellij project clean glob pattern in windows

---

packages/melos/lib/src/common/workspace.dart
packages/melos/test/workspace_test.dart

fix: The default workspace no-longer searches for projects inside the .dart_tool folder of packages

---

packages/conventional_commit/example/conventional_commit.dart
packages/conventional_commit/lib/conventional_commit.dart
packages/conventional_commit/pubspec.yaml
packages/conventional_commit/test/conventional_commit_test.dart
packages/melos/lib/src/command/version.dart

This also renamed `ConventionalCommit.parse` into `ConventionalCommit.tryParse` to match other Dart classes that return "null" when the parsing fails:
```
int? value = int.tryParse('')
```

feat!: migrate conventional_commit to null-safety

---

packages/melos/lib/src/command/base.dart
packages/melos/lib/src/command/exec.dart
packages/melos/lib/src/common/utils.dart

closes #15
closes #16
inspired by #16
- pass script source directly to shell using `-c` option
- ignore trailing options in exec command (exec tried to parse all available options including those passed to the child script)
same approach is used in `pub run` https://github.com/dart-lang/pub/blob/291705ca0b9632cb945dd39493dd5b9db41b897a/lib/src/command/run.dart#L27

fix: exec hang, exec trailing options

---

packages/melos/templates/intellij/modules/workspace_root_module.iml.tmpl

When you run `melos bootstrap` command it doesn't enable Dart SDK for the root module. This fixes the issue.
Fixes #124

fix: enable Dart SDK for root IntelliJ project

---

packages/conventional_commit/lib/conventional_commit.dart
packages/conventional_commit/test/conventional_commit_test.dart

Fixes a bug as discovered on the following commit from FlutterFire;
```
feat(*): Upgrade Firebase Android BoM version to 28.1.0 (#6338)
This fixes an issue with Cloud Firestore when retrieving data after the app has resumed from the background.
```

fix: commit scope should support asterisk characters

---

packages/melos/lib/src/command/version.dart

Issue due to an if statement being inverted incorrectly in a previous refactor.

fix: issue where dependent packages were not versioned

---

docs/index.md

I hope you are glad having [paddinger](https://github.com/ema987/paddinger) in the list of projects using Melos!

docs: Add ema987/paddinger as project using melos

---

README.md

The Wikipedia URL was pasted twice. Therefore, it would redirect to the incorrect URL and people could not learn more about Monorepo easily. This URL hopefully fixes that!

docs: Fix wikipedia redirect

---

docs.json
docs/environment-variables.mdx

In getting started with `melos` at my organization, I had trouble finding the information on these, so thought getting them into the docs would be nice. Transcribes https://github.com/invertase/melos/issues/3 into the documentation format. Realize there is some WIP [here](https://github.com/invertase/melos/pull/126), however would love to have something in the documentation at least until the next iteration of the documentation is published.

docs: Add documentation for environment variables

---

packages/melos/lib/src/commands/run.dart
packages/melos/lib/src/commands/runner.dart
packages/melos/lib/src/workspace.dart
packages/melos/test/package_filter_test.dart
packages/melos/test/package_test.dart
packages/melos/test/workspace_test.dart

This prevents the workspace config from being parsed multiple times under certain scenarios. At the same time, it helps to implement a cleaner solution to match unknown commands with scripts (#163).

refactor: Instantiate workspace from configs

---

packages/melos/bin/melos.dart
packages/melos/lib/src/command_runner.dart
packages/melos/lib/src/command_runner/base.dart
packages/melos/lib/src/command_runner/bootstrap.dart
packages/melos/lib/src/command_runner/clean.dart
packages/melos/lib/src/command_runner/exec.dart
packages/melos/lib/src/command_runner/list.dart
packages/melos/lib/src/command_runner/publish.dart
packages/melos/lib/src/command_runner/run.dart
packages/melos/lib/src/command_runner/version.dart
packages/melos/lib/src/commands/run.dart
packages/melos/lib/src/commands/runner.dart
packages/melos/lib/src/commands/version.dart
packages/melos/test/commands/bootstrap_test.dart
packages/melos/test/commands/exec_test.dart
packages/melos/test/commands/list_test.dart
packages/melos/test/commands/run_test.dart

To be able to match unknown commands with scripts (#163), the list of scripts must be known before parsing command-line arguments.
Thus, instead of reading the workspace config in individual commands, read the config early on startup and pass it down to the command runner and commands so that:
a) commands don't need to read the config again, and
b) it will be straightforward to introduce a new command that matches unknown commands with scripts.

refactor: Pass workspace config from the top

---

packages/melos/lib/src/command_runner.dart
packages/melos/lib/src/command_runner/script.dart
packages/melos/test/command_runner_test.dart
packages/melos/test/commands/script_test.dart

Allow running `melos <script>` as a shortcut for `melos run <script>`, provided that the script name doesn't conflict with built-in commands.
```yaml
name: test_workspace
packages: [packages/**]
scripts:
test: echo "running test script..."
clean: echo "running clean script..."
```
In the above workspace, `melos test` is equivalent to `melos run test`:
```
$ melos test
melos run test
└> echo "running test script..."
└> RUNNING
running test script...
melos run test
└> echo "running test script..."
└> SUCCESS
```
However, `melos clean` is a built-in command:
```
$ melos clean
Cleaning workspace...
Workspace cleaned. You will need to run the bootstrap command again to use this workspace.
```
Close: #163

feat: Match unknown commands with scripts

---

packages/melos/lib/src/commands/run.dart
packages/melos/lib/src/package.dart

Fixes FlutterFire CI erroring trying to run tests for packages that are actually ignored in melos.yaml

fix: melos.yaml ignores should apply also to `run` commands `MELOS_PACKAGES` env variable

---

packages/melos/lib/src/command_runner/version.dart
packages/melos/lib/src/commands/version.dart

Currently the value specified for `--depentens-versions` on the command line is not passed through to the `autoVersion` method.

fix: run version cmd with `--depentens-versions` value from cli

---

packages/melos/lib/src/commands/version.dart

If a dependent of a package declares an exact version constraint for that dependency, updating that version constraint as part of versioning, now replaces the old constraint with an exact constraint for the new version.

feat: respect exact version constraints when updating dependents

---

packages/melos/lib/src/commands/version.dart

feat: verbose logging now logs package commit messages when versioning

---

docs/configuration/overview.mdx
packages/melos/lib/src/common/git_repository.dart
packages/melos/test/git_repository_test.dart

This PR adds support for https://gitlab.com.
It does not support self-hosted instances at the moment. If I have missed anything that should be changed to support GitLab then I will obviously change that ;-).

feat: add repository host support for `GitLab`

---

packages/melos/pubspec.yaml

Resolves: https://github.com/invertase/melos/issues/239.
platform 3.0.0 uses a deprecated member that was removed in flutter 2.10.0. platform 3.1.0 resolves this.

fix: bump `platform` dependency to to 3.1.0 to support latest Flutter/Dart versions

---

packages/melos/lib/src/command_runner/version.dart
packages/melos/lib/src/common/utils.dart

fix: don't use `Enum.name`

---

docs/commands/list.mdx
packages/melos/lib/src/command_runner/list.dart
packages/melos/lib/src/commands/list.dart
packages/melos/test/commands/list_test.dart

Feature implementation for #246.

feat: add flag to show relative paths when using `list` (FR #246)

---

docs/guides/automated-releases.mdx
packages/conventional_commit/lib/conventional_commit.dart
packages/conventional_commit/test/conventional_commit_test.dart

This PR solves #258 by removing the first `^` from the check in `_conventionalCommitRegex`.
This enables users to use Melos on hosted git repositories where the system adds non-configurable prefixes when merging pull requests.
Example from Azure DevOps which uses `Merged`:
```
Merged PR 404: fix: Use correct path for signing
```

feat: allow prefixes before conventional commit type

---

packages/melos/lib/src/package.dart

Currently, the regex captured wrong version of the package. As we can see, I tried to find the version of `xetia_core` package, the expected result is ^1.12.0 but the actual result is "^1.0.0".
After this fix, the regex captured expected result as below:

fix: hosted dependency version regex

---

docs/commands/version.mdx

When using the shorthand syntax (`-V`), you don't use the equals (the shorthand is always a single character).
When using the complete syntax with `--`, the `=` is required (as documented).
Just updating a typo in the docs.

docs: Fix docs about `--manual-version (-V)`

---

docs/configuration/overview.mdx
docs/environment-variables.mdx
packages/melos/lib/melos.dart
packages/melos/lib/src/command_runner.dart
packages/melos/lib/src/command_runner/base.dart
packages/melos/lib/src/command_runner/bootstrap.dart
packages/melos/lib/src/command_runner/clean.dart
packages/melos/lib/src/command_runner/exec.dart
packages/melos/lib/src/command_runner/list.dart
packages/melos/lib/src/command_runner/publish.dart
packages/melos/lib/src/command_runner/version.dart
packages/melos/lib/src/commands/bootstrap.dart
packages/melos/lib/src/commands/clean.dart
packages/melos/lib/src/commands/exec.dart
packages/melos/lib/src/commands/list.dart
packages/melos/lib/src/commands/publish.dart
packages/melos/lib/src/commands/run.dart
packages/melos/lib/src/commands/runner.dart
packages/melos/lib/src/commands/version.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/common/validation.dart
packages/melos/lib/src/global_options.dart
packages/melos/lib/src/package.dart
packages/melos/lib/src/workspace.dart
packages/melos/lib/src/workspace_configs.dart
packages/melos/test/commands/bootstrap_test.dart
packages/melos/test/mock_workspace_fs.dart
packages/melos/test/utils.dart
packages/melos/test/utils_test.dart
packages/melos/test/workspace_test.dart

This PR adds support for specifying the path to a Dart/Flutter SDK, instead of relying on what's in the path. 
This makes melos compatible with flutter version manager (fvm).
The SDK path can be specified though the following mechanisms, in order of highest to lowest precedence:
1. `--sdk-path` command line option
2. `MELOS_SDK_PATH` environment variable
3. `sdkPath` in `melos.yaml`
Closes #81

feat: add support for Dart/Flutter SDK at custom `sdkPath`

---

packages/melos/README.md

The `pub` command was removed. Instead, we should use `dart pub`.

docs: use `dart pub` instead of `pub` in `README.md`

---

packages/melos/lib/src/common/changelog.dart
packages/melos/lib/src/common/git_repository.dart
packages/melos/test/changelog_test.dart
packages/melos/test/git_repository_test.dart

feat: link to referenced issues/PRs in changelog

---

packages/melos/lib/src/common/utils.dart
packages/melos/test/test_assets/dart_wrapper
packages/melos/test/test_assets/dart_wrapper.bat
packages/melos/test/utils_test.dart

When trying to get the dart version, `dart --version` should be run inside a separate shell to avoid failing when running in a sub process.
The failing of this command is actually used here:
https://github.com/invertase/melos/blob/431ecb275bf7169d71f9c19e4593abd3274a46ca/packages/melos/lib/src/common/utils.dart#L404-L411
This bug was introduced in https://github.com/invertase/melos/commit/740050c4dd67938d0674ddd37f0291d52f331bd4 since it changed how to dart version is retrieved.

fix: Run Process.runSync in another shell to get Dart version

---

packages/melos/lib/src/commands/list.dart
packages/melos/lib/src/package.dart
packages/melos/test/commands/list_test.dart
packages/melos/test/mock_workspace_fs.dart

fix: report all dependencies in `list` command

---

docs/configuration/scripts.mdx
docs/getting-started.mdx
packages/melos/lib/src/commands/run.dart
packages/melos/lib/src/scripts.dart
packages/melos/test/commands/run_test.dart
packages/melos/test/workspace_config_test.dart

This change adds the `exec` option to scripts,  which simplifies writing scripts that are executed in multiple packages through `melos exec`.

feat: add `exec` option to scripts

---

README.md
docs/filters.mdx
melos.yaml
packages/melos/lib/melos.dart
packages/melos/lib/src/command_runner/base.dart
packages/melos/lib/src/common/git.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/package.dart
packages/melos/lib/src/scripts.dart

We found it extremely helpful to have the possibility to run melos on packages that are different between branches. As the `since` option does not really work with the difference I propose to introduce a `diff` option that will call `git diff` instead of `git log`.
The usage might be:
```sh
melos list --diff=some_branch
```
or
```sh
melos list --diff=origin/main...HEAD
```

feat: Add --diff filter

---

docs/configuration/overview.mdx
melos.yaml
packages/melos/lib/src/package.dart
packages/melos/lib/src/workspace_configs.dart
packages/melos/test/workspace_test.dart

Before this change, the `packages` and `ignore` patterns had to match `pubspec.yaml` for a package to be found.
Now packages are also found if a pattern matches a directory that contains a package.

fix: find packages in matched directories

---

packages/melos/lib/src/package.dart

It is possible that `resolvePackages` finds the same package twice, under paths that point to the same location but are represented by `String`s that are not equal.
This change ensures a package is only found once by using functions from  `package:path` for using paths as keys in a `Map`.

fix: false positive for non-unique packages

---

docs/commands/clean.mdx
packages/melos/lib/src/common/intellij_project.dart

fix: don't override Intellij module config files

---

packages/melos/lib/src/scripts.dart

`--fail-fast` is a flag and not an option and as such does not accept any value.
This config is currently broken as in the generated command `--fail-fast true` is not valid syntax.
```yaml
scripts:
lint:
run: flutter analyze
exec:
failFast: true
concurrency: 1
```

fix: `scripts.*.exec.failFast` option in `melos.yaml`

---

packages/melos/lib/src/commands/bootstrap.dart
packages/melos/lib/src/commands/exec.dart
packages/melos/lib/src/commands/run.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/workspace.dart
packages/melos/test/utils_test.dart

This change removes `runInShell: true` from `Process.start` when
executing commands. This option is unnecessary since Melos is spawning
a shell itself to execute the command. Using `runInShell: true`
becomes a problem for command chains (e.g. '&&' or '||').
In this case only the first command is executed in the shell that Melos
is spawning and the rest of the commands are executed in the shell
spawned by `Process.start`.
The change also cleans up a few other related bits of code.
Fixes #367

fix: run commands in single shell

---

docs/index.mdx
packages/melos/README.md

add [yak_packages](https://github.com/iapicca/yak_packages) to [docs/index]([docs](https://github.com/invertase/melos/edit/main/docs/index.mdx))
it's a mono repo for the following packages:
| Package | Link |
|--------|-----|
| [byte_token](https://github.com/iapicca/yak_packages/tree/master/packages/byte_token) | [pub](https://pub.dev/packages/byte_token) |
| [stub](https://github.com/iapicca/yak_packages/tree/master/packages/stub) | [pub](https://pub.dev/packages/stub) |
| [yak_flutter](https://github.com/iapicca/yak_packages/tree/master/packages/yak_flutter) | [pub](https://pub.dev/packages/yak_flutter) |
| [yak_result](https://github.com/iapicca/yak_packages/tree/master/packages/yak_result) | [pub](https://pub.dev/packages/yak_result) |
| …

docs: add yak_packages reference to docs/index

---

docs/commands/version.mdx
packages/melos/lib/src/command_runner/version.dart
packages/melos/lib/src/commands/version.dart

Previously, the preid of dependents was always `dev`.
Now `--preid` is used, if provided, unless `--dependent-preid` is provided.
Fixes #310

feat: add `--dependent-preid` option

---

packages/melos/lib/src/package.dart
packages/melos/test/package_test.dart

fix: only include normal dependencies of transitive dependencies

---

packages/melos/lib/src/common/git.dart
packages/melos/lib/src/workspace.dart

`Process.run()` uses the default [system encoding ](https://api.dart.dev/stable/2.18.3/dart-io/systemEncoding-constant.html) for stderr/stdout. Only on Windows this default to the active code page while on other systems this is always UTF-8. This commit forces `Process.run()` to use UTF-8 in all places and thus handle e.g. Chinese characters correctly.
Fixes #411.

fix: unicode characters in commit titles

---

packages/conventional_commit/test/conventional_commit_test.dart
packages/melos/lib/src/common/changelog.dart
packages/melos/lib/src/common/versioning.dart
packages/melos/test/changelog_test.dart
packages/melos/test/common/versioning_test.dart

Merge commits were not versioned. Example:
```Merged PR 123: fix(3305): change url launcher to open externally```
Fixes a regression of #258.
Me and @spydon fixed this together :)

fix: Merge commits should be versioned

---

docs/configuration/overview.mdx
packages/melos/lib/src/common/git_repository.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/workspace_configs.dart
packages/melos/test/git_repository_test.dart
packages/melos/test/workspace_config_test.dart
pubspec.yaml

This PR implements support for self-hosted git repositories. This configuration syntax for this is as follows:
```yaml
repository:
type: gitlab
base: https://gitlab.example.dev
owner: invertase
name: melos
```
I initially tried to use RegEx to extract this information from only the URL, but GitLab supports both subgroups and hosting not on the root of a domain. This means that `https://example.com/gitlab/invertase/melos` could be both a GitLab instance on `https://example.com/gitlab` with a group named `invertase` or an instance on `https://example.com/` with a group/subgroup of `gitlab/invertase`. I was also tempted to validate the owner/name fields using RegEx, but at least for GitLab the [patterns](https://gitlab.com/gitlab-org/gitlab/-/blob/0890bda6ba241539914cd95fcc83bbcc7960c953/lib/ …

feat: support self-hosted git repositories

---

.github/workflows/validate.yaml
all_lint_rules.yaml
docs/configuration/overview.mdx
docs/getting-started.mdx
packages/conventional_commit/lib/conventional_commit.dart
packages/conventional_commit/pubspec.yaml
packages/melos/lib/src/command_runner/bootstrap.dart
packages/melos/lib/src/command_runner/clean.dart
packages/melos/lib/src/command_runner/exec.dart
packages/melos/lib/src/command_runner/list.dart
packages/melos/lib/src/command_runner/publish.dart
packages/melos/lib/src/command_runner/run.dart
packages/melos/lib/src/command_runner/script.dart
packages/melos/lib/src/command_runner/version.dart
packages/melos/lib/src/commands/bootstrap.dart
packages/melos/lib/src/common/git_commit.dart
packages/melos/lib/src/common/git_repository.dart
packages/melos/lib/src/common/pub_dependency_list.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/package.dart
packages/melos/lib/src/scripts.dart
packages/melos/lib/src/workspace.dart
packages/melos/pubspec.yaml
packages/melos/test/commands/bootstrap_test.dart
packages/melos/test/commands/clean_test.dart
packages/melos/test/melos_test.dart
packages/melos/test/test_assets/add_to_app_json.json
packages/melos/test/utils.dart
pubspec.yaml

feat!: upgrade minimum Dart SDK version to 2.18.0

---

.vscode/settings.json
docs/configuration/overview.mdx
packages/melos/lib/src/common/io.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/package.dart
packages/melos/pubspec.yaml
packages/melos/test/commands/list_test.dart
packages/melos/test/workspace_test.dart

Before this change all files in a workspace were iterated over to find packages.
`Glob.list` can potentially skip searching through many directories based on the pattern. In larger workspaces this can save upwards of 300ms during each invocation.

perf: use `Glob.list` to more efficiently find packages

---

docs/configuration/overview.mdx
packages/melos/lib/src/commands/bootstrap.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/package.dart
packages/melos/lib/src/workspace.dart
packages/melos/lib/src/workspace_configs.dart
packages/melos/test/utils.dart
packages/melos/test/utils_test.dart
packages/melos/test/workspace_config_test.dart

This adds two related features related to the feature request #409.
1) Adds a `melos_overrides.yaml` file, that can be used to override any field in `melos.yaml` (for making local, untracked changes)
Example use cases: local `dependency_overrides`, customized IDE project generation
2) Adds a `dependency_overrides` configuration option, to add non-workspace packages to each package's `dependency_overrides.yaml`.

feat: add support for `melos_overrides.yaml` + `command/bootstrap/dependencyOverridePaths`

---

packages/melos/lib/src/common/io.dart

I'm regularly having an issue with melos not being able to delete some file or folder.
Turns out it was the `.dart_tool/melos_tool` folder.
Just in order to give the user a clue as to what is going wrong, I'd like to add the `path` of the `FileSystemException` to the `IOException being thrown`

feat: add path to `IOException` message

---

docs/configuration/scripts.mdx
packages/melos/lib/src/command_runner/exec.dart
packages/melos/lib/src/commands/exec.dart
packages/melos/lib/src/commands/publish.dart
packages/melos/lib/src/scripts.dart
packages/melos/test/commands/exec_test.dart
packages/melos/test/workspace_config_test.dart

Add `--require-dependencies` flag to exec to require the dependencies of a package be exec'd before the package itself.
As part of this, reorder the exec's to be topological like publish.
I believe this should close #433

feat: support running scripts in topological order with `melos exec`

---

docs/commands/version.mdx

Fixed a wrong description in the documentation.

docs: fix description of git-tag-version option

---

docs/commands/bootstrap.mdx
docs/filters.mdx
docs/guides/automated-releases.mdx
docs/guides/migrations.mdx
packages/melos/README.md
packages/melos/lib/src/command_runner/base.dart
packages/melos/lib/src/commands/version.dart
packages/melos/lib/src/common/git.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/package.dart
packages/melos/test/package_test.dart

feat!: remove `--since` filter in favour of `--diff`

---

packages/melos/lib/src/commands/version.dart
packages/melos/lib/src/package.dart
packages/melos/test/package_test.dart

Fix #455 
The expression did not allow the patch version for `0.` packages.

fix: updateGitTagRefs not working for versions like 0.1.2+3

---

.github/workflows/scripts/install-tools.bat
.github/workflows/scripts/install-tools.sh
CONTRIBUTING.md
all_lint_rules.yaml
analysis_options.yaml
docs/getting-started.mdx
docs/guides/migrations.mdx
melos.yaml
packages/melos/README.md
packages/melos/bin/melos.dart
packages/melos/lib/src/command_runner.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/workspace_configs.dart
packages/melos/pubspec.yaml
packages/melos/test/command_runner_test.dart
packages/melos/test/commands/bootstrap_test.dart
packages/melos/test/commands/clean_test.dart
packages/melos/test/commands/exec_test.dart
packages/melos/test/commands/list_test.dart
packages/melos/test/commands/run_test.dart
packages/melos/test/commands/script_test.dart
packages/melos/test/package_filter_test.dart
packages/melos/test/package_test.dart
packages/melos/test/utils.dart
packages/melos/test/utils_test.dart
packages/melos/test/workspace_test.dart
pubspec.yaml

Before this change, versioning of Melos by users was not enforced. Most users installed Melos globally, and without specify a version, on development as well as CI machines. That means potentially breaking versions of Melos were adopted without the users' knowledge.
With this change, users are required to add a dependency on `melos` to a `pubspec.yaml` file, next to the `melos.yaml` file. The globally installed `melos` executable will hand over to the locally installed version if their versions are different. This ensures that the version of Melos used is always the correct one for the workspace the user is currently working in.

feat!: local installation of melos in workspace

---

.github/workflows/validate.yaml

Node 12 is deprecated for GitHub Actions. This is the reason why GitHub shows us a warning:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
This PR updates `actions/checkout` from v2 to v3 which should fix the problem.

ci: update `actions/checkout` from v2 to v3 in our GitHub workflows

---

packages/melos/lib/src/package.dart
packages/melos/test/package_test.dart

Unpub doesn't support querying "/packages/[package-name].json" which is used for querying the published versions of a package.
This PR switches to the "/api/packages/[package-name]" endpoint that is supported by pub.dev and Unpub.

fix: change used API endpoint for querying versions

---

docs/getting-started.mdx

- Fixed a small typo. _Installe_ should be _Install_

docs: fix a typo in getting started section

---

.github/workflows/latest_melos_release.yaml
packages/melos/README.md
packages/melos/example/README.md
packages/melos/pubspec.yaml

docs: pin docs to latest Melos release

---

packages/melos/pubspec.yaml

Updated the cli_util dependency from 0.3.0 to 0.4.0 some people were expressing it was creating conflicts with other packages, running test coverage showed the same result before and after the change.
- [ x] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)

chore: expand `cli_util` version constraint to include 0.4.0

---

packages/melos/pubspec.yaml

Currently melos is not compatible to packages like `dart_code_metrics ^5.7.4` because of a version conflict with `pub_updater`. Version `0.3.0` of pub_updater has been released that fixes bugs.
I have therefore set the version of `pub_updater` for melos to `^0.3.0`.

chore: update `pub_updater` to 0.3.0

---

packages/melos/pubspec.yaml

The `http` package was updated to `1.0.0`. There are no change that affect usage (it just adds new class restrictions), so this extends all dependencies to include both `0.13.x` and `1.x.x`.
fixes: #532

chore: widen constraints to allow `http` 1.0.0

---

docs/commands/bootstrap.mdx
melos.yaml
packages/melos/lib/src/commands/bootstrap.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/workspace_configs.dart
packages/melos/test/commands/bootstrap_test.dart
packages/melos/test/utils.dart

**NOTE:** I'm adding this as a draft PR as docs and tests are not yet added and I haven't yet added feedback if the user turned on the flag but didn't provide the `common_packages.yaml`-file. But I wish for feedback on my solution anyways.
Added support for setting versions for common/shared dependencies that will be applied to all packages in a Melos monorepo project. Implements #94.
A new bootstrap config flag (`shareDependencies`) is added to start using this new feature, and then the dependency versions for `dependencies` and `dev_dependencies` in `common_packages.yaml` will be applied to all packages that contains said dependency.

feat: Sync common dependency versions between packages

---

packages/melos/lib/src/common/intellij_project.dart
packages/melos/test/common/intellij_project_test.dart

Resolves #581.
Replace all `\` with `/` regardless of platforms.

fix: `.idea/modules.xml` should always uses `/` instead of `\`

---

packages/melos/lib/src/commands/exec.dart
packages/melos/lib/src/commands/list.dart

The analyzer is currently failing with the newest dart version, this fix simply removes the unnecessary parenthesis so that `analyze` becomes green again.

refactor: Remove unnecessary parenthesis to get analyzer green

---

docs/commands/version.mdx
docs/guides/automated-releases.mdx

Added examples on how to manually version multiple packages via `melos version` command. Additionally fixed a few typos.
Closes #586

docs: Add examples of manual versioning of multiple packages

---

packages/melos/lib/src/common/changelog.dart
packages/melos/lib/src/workspace_configs.dart

This PR introduces a new version command option:
```yaml
command:
version:
includeCommitBody: true # default is false
```
This might be useful for PRs with breaking changes (migration guides could be added to changelog from commit boides)

feat: add option that allows to include commit bodies in changelog

---

docs/configuration/overview.mdx
packages/melos/lib/src/common/git_repository.dart
packages/melos/test/git_repository_test.dart

Basic integration with Bitbucket git repository url. It allows to generate changelog with proper commit urls.
**It does not provide support of issue Url generation** as bitbucket  use Jira as issue tracker and it would require to pass additional Jira url in the config files. Adding Jira support require to rebuild bigger chunk of the code (additional configs, default behavior, new issue tracking regexp, more tests).  It can be done in next MR.

feat: add support for bitbucket repository url

---

packages/melos/lib/src/command_runner/bootstrap.dart

feat: add another alias to `melos bootstrap`
Adding this change, that i already use on a local fork of melos, to the repo.

feat: add another alias to `melos bootstrap`

---

docs/getting-started.mdx

While the _Getting Started_ document tells the user about the importance of bootstrapping, the actual `melos bootstrap` command is neither shown nor executed. This is not a major problem, but I tripped over it while following the instructions, so I suspect it may irritate others as well.
Thus, I made that small addition.
refs #565
- [] ✅ `ci` -- Build configuration change

docs: added missing execution of `melos bootstrap` in getting started file

---

docs/commands/bootstrap.mdx
packages/melos/lib/src/command_runner/bootstrap.dart
packages/melos/lib/src/commands/bootstrap.dart

- add ``` --no-example ``` arg for ```dart/flutter pub get``` of bootstrap command [https://github.com/dart-lang/pub/pull/3856](url)
```
melos bs --no-example
```
- [ x] ✨ `feat` -- New feature (non-breaking change which adds functionality)

feat: add "--no-example" arg to "pub get " command for melos bootstrap

---

packages/melos/lib/melos.dart
packages/melos/lib/src/workspace_configs.dart
packages/melos/test/command_runner_test.dart
packages/melos/test/commands/run_test.dart
packages/melos/test/workspace_config_test.dart

Resolves: https://github.com/invertase/melos/issues/572

fix: Expose script api

---

packages/melos/lib/src/commands/publish.dart
packages/melos/lib/src/common/http.dart
packages/melos/lib/src/common/pub_credential.dart
packages/melos/lib/src/common/pub_hosted.dart
packages/melos/lib/src/common/pub_hosted_package.dart
packages/melos/lib/src/package.dart
packages/melos/test/package_test.dart
packages/melos/test/utils.dart

Support authentication with private pub repositories.
Resolves: https://github.com/invertase/melos/issues/498

feat: Support authentication private pub

---

packages/melos/lib/src/command_runner/version.dart
packages/melos/lib/src/commands/version.dart

This adds the `--git-commit-version`/`--no-git-commit-version` flags to control commit creation, since this no longer will be omitted after #625 is merged and `-t` is used.
This PR has #625 as a base, so that needs to be merged first.

feat: Add `git-commit-version` flag to control commit creation

---

.github/workflows/validate.yaml
melos.yaml
packages/conventional_commit/pubspec.yaml
packages/melos/lib/src/common/versioning.dart
packages/melos/pubspec.yaml
pubspec.yaml

Simply updates the min version of the Dart SDK to 3.0.0.

chore: Update min version of Dart SDK to 3.0.0

---

docs/environment-variables.mdx
packages/melos/lib/src/commands/run.dart
packages/melos/lib/src/commands/runner.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/package.dart
packages/melos/test/commands/run_test.dart

There are **2 key changes here**:
- `melos run` command now also takes `MELOS_PACKAGES` value into account.
- `MELOS_PACKAGES` is not used instead of filters, but it adds or replaces the `scope` in the `PackageFilters`.
Considering [the current definition](https://melos.invertase.dev/environment-variables#melos_packages) of  `MELOS_PACKAGES` that says 'This bypasses all filtering flags if defined.' the current change looks like a breaking change to me.
**A bit more context**:
We have quite a big monorepo (100+ packages) on my current project. In our CI pipeline, we trigger the CI checks for certain subfolders/packages (based on which areas are affected by a PR). 
We already have this kind of setup running with Melos 2.9, but it was achieved by different means, and we'd love to migrate to …

feat!: make run script use melos_packages env variable scope

---

docs/index.mdx
packages/melos/README.md

I was going through the list of projects using Melos in the docs and noticed that [amplify-flutter](https://github.com/aws-amplify/amplify-flutter) doesn't use Melos anymore. It migrated away from using it in [this PR](https://github.com/aws-amplify/amplify-flutter/pull/3065/files). So, let's reflect that in the documentation.

docs: remove `amplify-flutter` from projects using Melos

---

packages/melos/lib/src/commands/exec.dart
packages/melos/lib/src/commands/run.dart
packages/melos/lib/src/commands/runner.dart
packages/melos/lib/src/common/environment_variable_key.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/package.dart
packages/melos/lib/src/workspace.dart
packages/melos/test/commands/run_test.dart
packages/melos/test/workspace_test.dart

Extracted the duplicated and spread through different places environment keys into one class to have a more maintainable approach.

refactor: move environment variable related strings into one class

---

all_lint_rules.yaml
packages/melos/lib/src/common/pub_dependency_list.dart
packages/melos/lib/src/workspace_configs.dart

Updated `all_lint_rules.yaml` file with the actual rules that are listed at `https://dart.dev/tools/linter-rules/all`. 
I don't expect any issues even though this auto-generated list of rules is based on Dart 3.3.0 and the current SDK constraint on the package level is `>=3.0.0 <4.0.0`. 
The fact that the removed from rules do not exist anymore can be checked on https://dart.dev/tools/linter-rules page, for example https://dart.dev/tools/linter-rules/avoid_as.

chore: update all_lint_rules list

---

packages/melos/lib/src/common/git.dart

Use `git pull --tags` instead of `git fetch --tags`. The problem with using `fetch` - the tag needs to be associated with a branch that is on remote. If it isn't (i.e. usually squashed and merge) it will not be retrieved and will remain orphaned on remote.
Using `git pull --tags` will pull all tags no matter the status of the branch.

fix: use `git pull --tags` instead of `git fetch --tags`

---

packages/melos/lib/src/command_runner/exec.dart
packages/melos/lib/src/commands/exec.dart

This PR removes the hardcoded (5) value of concurrency for exec and replaces it with a dynamic value based on the number of processors in the computer.

feat: Default to number of processors for exec concurrency

---

docs/commands/analyze.mdx
melos.yaml
packages/melos/README.md
packages/melos/lib/src/command_runner.dart
packages/melos/lib/src/command_runner/analyze.dart
packages/melos/lib/src/commands/analyze.dart
packages/melos/lib/src/commands/runner.dart
packages/melos/test/commands/analyze_test.dart

First things first, I'm really excited to work on this issue because this year I made a personal goal to contribute more to open source projects. It makes me happy to be able to do it for a tool that I use every day. 
Usually, melos projects use a script to run either `dart analyze` or `flutter analyze`, as mentioned by @jpnurmi  in issue #424. However, I agree that it would be better to have a built-in command for this. Some newbies to the tool might try running this command and then realize they need extra setup to get the same results.
So, this pull request aims to address this problem by adding the needed functionality. It also includes features like running tasks concurrently, filtering, and support for `--fatal-infos` and `--[no-]fatal-warnings` options.
I also took the time to …

feat: built-in melos command for analyzing projects

---

docs/commands/publish.mdx
docs/configuration/scripts.mdx
docs/environment-variables.mdx
packages/melos/lib/src/command_configs/command_configs.dart
packages/melos/lib/src/command_configs/publish.dart
packages/melos/lib/src/command_runner/publish.dart
packages/melos/lib/src/commands/bootstrap.dart
packages/melos/lib/src/commands/clean.dart
packages/melos/lib/src/commands/exec.dart
packages/melos/lib/src/commands/publish.dart
packages/melos/lib/src/commands/runner.dart
packages/melos/lib/src/commands/version.dart
packages/melos/lib/src/common/environment_variable_key.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/lifecycle_hooks/publish.dart
packages/melos/test/commands/publish_test.dart

This PR adds lifecycle hooks (`pre` and `post`) to the `publish` command.
It runs `pre` once before publishing runs and `post` once afterwards (even though several packages might be published).
It also runs in `--dry-run` mode, to better emulate a real publish.
The environment variable `MELOS_PUBLISH_DRY_RUN` is introduced so that the user can know whether it is in `dry-run` mode or not in the scripts.

feat: Add lifecycle hooks for `publish`

---

.github/workflows/validate.yaml
docs/commands/format.mdx
melos.yaml
packages/melos/README.md
packages/melos/lib/src/command_runner.dart
packages/melos/lib/src/command_runner/format.dart
packages/melos/lib/src/commands/format.dart
packages/melos/lib/src/commands/runner.dart
packages/melos/test/commands/format_test.dart

This PR introduces a new built-in command called "format" that follows the same implementation logic used in the development of the "analyze" command, which was merged in a previous ([PR](https://github.com/invertase/melos/pull/655)). The purpose of this change is to eliminate the need to set up a separate script in order to format each package.
For example, instead of using the following YAML configuration:
```yaml
scripts:
format:
description: Format Dart code.
run: dart format .
format:check:
description: Check formatting of Dart code.
run: dart format --output none --set-exit-if-changed .
```
The first script can now be replaced with a simpler command: `melos format`. Similarly, the second script can be replaced with `melos format --output none --set-exit-if-changed`.
Additionally, …

feat: format built in command

---

docs/configuration/scripts.mdx
packages/melos/lib/src/commands/run.dart
packages/melos/lib/src/scripts.dart
packages/melos/test/commands/run_test.dart

This PR adds the capability to combine multiple scripts into a single script definition. In the provided example, the `pre-commit` script is configured to invoke a simple command as `echo 'hello world'`, and also individual scripts such as `format` and `analyze`.
```yaml
scripts:
pre-commit:
description: pre-commit git hook script
steps:
- echo 'hello world'
- format
- analyze
format:
description: Format Dart code.
run: dart format .
exec:
concurrency: 5
analyze:
description: Analyze Dart code
run: dart analyze .
exec:
concurrency: 5
```
```console
┌─(~/Development/melos)──────────────────────────────────────────────────────────────────────────────────────────────────────────(jessica@jessicas-MacBook-Air:s005)─┐
└─(21:14:01 on feature/multiple-steps-script ✹)──> melos run pre-commit …
```

feat: add support for combining scripts

---

packages/melos/lib/src/common/git.dart
packages/melos/lib/src/package.dart

Opening up #558 again since Blaugold saw no problem with it.
This reverts to the original diff functionality.
Closes #557

fix: fix diff functionality

---

packages/melos/lib/src/command_runner/exec.dart
packages/melos/lib/src/commands/exec.dart
packages/melos/lib/src/commands/runner.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/logging.dart
packages/melos/pubspec.yaml
packages/melos/test/commands/exec_test.dart

The expected behavior of failFast option is to fail the whole exec command as soon as a single fail occurs, and it works as expected if concurrency=1. But if concurrency > 1, it diverges from the expected behavior and instead keeps running until all pooled jobs have finished executing.
This PR fixes this divergence, and the exec command will fail immediately on a single fail irrespective of concurrency value.

fix: exec command with failFast should fail immediately

---

packages/melos/lib/src/commands/analyze.dart
packages/melos/test/commands/analyze_test.dart

This PR aims to fix a problem with the log output of the analyze command when the concurrency flag is used, as reported in issue #668. 
Closes #668

fix: melos analyze concurrency flag log output

---

packages/melos/lib/src/commands/analyze.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/logging.dart
packages/melos/test/commands/analyze_test.dart

issue #668 
Improvements `melos analyse` log so that the output is the same when the `-c` option is specified as when it is not specified.
The `String? group` property is added for grouping when logging output. In the case of `-c 1`, this option is not needed. (Log output is done sequentially.) In the case of `-c 2`, all logs are output after the process is complete.
Existing buffer-flush was deprecated, so it was named group-buffer for convenience. If that is not good, please point it out. Thanks for the useful tools.
<details open><summary>main branch log</summary>
```console
$ melos analyze -c 1
Building package executable...
Built melos:melos.
$ melos analyze
└> dart analyze
└> RUNNING (in 3 packages)
------------------------------------------------------------------------------------- …
```

feat: Change concurrent log to sequential log

---

docs/commands/bootstrap.mdx
packages/melos/lib/src/command_runner/bootstrap.dart
packages/melos/lib/src/commands/bootstrap.dart
packages/melos/test/commands/bootstrap_test.dart

Fixes: #682 
Adds a new flag `--skip-linking` to the melos `bs`.
- with `--skip-linking` enabled
```zsh
melos bootstrap
└> /Users/sahilkumar/StudioProjects/melos
Updating common dependencies in workspace packages...
✓ melos
└> Updated environment
✓ melos_workspace
└> Updated environment
✓ conventional_commit
└> Updated environment
> SUCCESS
Generating IntelliJ IDE files...
> SUCCESS
-> 3 packages bootstrapped
```
- with `--skip-linking` disabled
```zsh
melos bootstrap
└> /Users/sahilkumar/StudioProjects/melos
Updating common dependencies in workspace packages...
✓ conventional_commit
└> Updated environment
✓ melos
└> Updated environment
✓ melos_workspace
└> Updated environment
> SUCCESS
Running "dart pub get" in workspace packages...
✓ conventional_commit
└> packages/conventional_commit
✓ …
```

feat: add support for `melos bs --skip-linking`

---

docs/configuration/scripts.mdx
packages/melos/lib/src/commands/run.dart
packages/melos/test/commands/run_test.dart

This pull request introduces support for melos command within script steps, as suggested in issue #653. An example configuration demonstrating this new capability is as follows:
```yaml
scripts:
pre-commit:
description: pre-commit git hook script
steps:
- echo 'hello world'
- format --output none --set-exit-if-changed
- analyze --fatal-infos
``` 
I'll need some help on determining the appropriate range of commands to support. Should we use every command possible?  
Currently, the following commands are under consideration:
```dart
const melosCommands = {
'analyze',
'format',
'bs',
'bootstrap',
'clean',
'list',
'publish',
};
```

feat: support for melos command within script steps

---

packages/melos/test/commands/run_test.dart

In the latest commit a1da197 merged into the main branch, a flaky test was introduced that affects Linux environments (my bad 😅):
```console
Expected: ... UNNING\n\n$ melos an ...
Actual: ... UNNING\n\nResolving  ...
^
Differ at offset 71
```
To address this issue, this PR aims to fix the flaky test and update all expected results of the `run_test` test suite to utilize the `ignoringDependencyMessages` matcher util.

test: refactor test expectations to use ignoringDependencyMessages

---

CHANGELOG.md
packages/melos/CHANGELOG.md
packages/melos/lib/version.g.dart
packages/melos/pubspec.yaml

```
The following 1 packages will be updated:
Package Name   Current Version   Updated Version   Update Reason
melos          5.2.2             5.3.0             updated with minor changes
```

chore(release): publish packages

---

packages/melos/lib/src/command_runner/format.dart
packages/melos/lib/src/commands/format.dart
packages/melos/test/commands/run_test.dart

This pull request adds a `--line-length` option to the `melos format` command, 
allowing users to specify the desired line length when formatting Dart code across packages in a Melos workspace.

feat: add `--line-length` option to `melos format` command

---

.vscode/settings.json
docs/commands/analyze.mdx
packages/melos/lib/src/commands/analyze.dart

The recent `melos analyze` changes came as a breaking change surprise for our project. On our project, we do not treat info-level issues as errors because we have some `deprecated` info lints in our codebase. 
The change introduced in https://github.com/invertase/melos/pull/655 results in the call to `flutter analyze` or `dart analyze` depending on the Flutter dependency presence.
**The issue is that those commands have different default behavior and configuration options.**
While `dart analyze` does not fail on info-level issues by default,
the `flutter analyze` does fail on info-level issues.
This results in inconsistent behavior. Also, it is not aligned with the [current documentation/API](https://melos.invertase.dev/commands/analyze#--fatal-infos) of `melos analyze`.
Since `dart …

fix!: Make `melos analyze` always use `dart analyze`

---

docs/filters.mdx
packages/melos/README.md
packages/melos/lib/src/package.dart
packages/melos/test/workspace_config_test.dart

I noticed that [the filters documentation](https://melos.invertase.dev/filters) was missing the information about `--include-dependencies` and `--include-dependents` options that were implemented in https://github.com/invertase/melos/pull/83, so it is added in this PR. In addition to that, I made it possible to provide these options in the `packageFilters` yaml configuration.

feat: option to provide dependencies related filters from yaml

---

packages/melos/README.md

It fixes the tiny misalignment in the Readme file I made [in the previous PR](https://github.com/invertase/melos/pull/698).

docs: fix misalignment in readme

---

packages/melos/lib/src/command_runner/format.dart
packages/melos/test/commands/format_test.dart

The flag `--line-length` was added, but it seems like it doesn't work as ArgParser doesn't seem to transform this param to int by default. This fix takes the `String` argument and tries parsing it to an `int`.

fix: tryParse line-length to int when it's not already an integer

---

packages/melos/lib/src/commands/version.dart
packages/melos/lib/src/common/aggregate_changelog.dart
packages/melos/test/commands/version_test.dart

Bug description: We bumped into this while having automated release to private hosting. Consider package B has dependency on A. If A was updated and we do not want do update constraint in B nor its version (we don't want due excessive publishing because we have fully automated release process), it was still mentioned in `melos version` log that B is getting bumped and also in the workspace changelog.
Fixes #531 - But I think it should check `updateDependentsVersions` and not `updateDependentsConstraints` like in the issue. Because if we update constraint it should not reflect to changelog, right ?

fix: `updateDependentsVersions` disabled with packages still mentioned in changelogs

---

.github/workflows/validate.yaml
packages/melos/lib/src/commands/exec.dart

Since #724 is blocking PRs to be merged we have to temporarily disable the failing macos test status in the pipeline (they still run).

ci: Temporarily set macos tests to not fail

---

.github/workflows/validate.yaml
packages/melos/test/matchers.dart

Hey everyone! I initially attempted to resolve this issue by following the approach mentioned in [this issue](https://github.com/dart-lang/pub/issues/3998) by setting the environment variable `PUB_SUMMARY_ONLY=1` in the workflow. However, this did not work as expected.
Then, I decided to solve it by updating the `ignoringDependencyMessages` method in the matcher file, and this approach seems to be working fine.
**Changes:**
- Remove unnecessary TODO comment in the workflow file
- Update test command in workflow to remove unnecessary `|| true`
- Update dependency messages matcher in `matchers.dart` test file
Issue: https://github.com/invertase/melos/issues/724

fix: Flaky tests when run in GitHub Actions Workflow

---

docs/index.mdx

Thank you for a great project.
Adds [GraphQL Codegen](https://github.com/heftapp/graphql_codegen) to the list of projects using Melos.

docs: Add project to list of Melos users

---

packages/melos/README.md

docs: Add signals to list of projects using Melos

---

packages/melos/lib/src/commands/run.dart
packages/melos/lib/src/commands/runner.dart
packages/melos/lib/src/common/persistent_shell.dart
packages/melos/lib/src/common/utils.dart
packages/melos/lib/src/logging.dart
packages/melos/test/commands/run_test.dart

This PR addresses the issue raised in #470, where the working directory is not maintained across multiple steps in a script.
For example, consider the following script:
```yaml
fail:
steps:
- cd packages/
- pwd
```
When running this script using melos run, the output will show the workspace root directory, not the `packages/` directory as expected.
This PR introduces a change to ensure that the working directory is properly maintained across multiple steps in a script.
The key changes are:
- Modify the script execution logic to preserve the working directory from one step to the next.
- Add a safeguard to prevent users from mixing && operators with multi-step scripts, as this can lead to unexpected behavior.
By running the script defined in the issue with the fix implemented in this PR, …

fix: maintain working directory across script steps

---

docs/commands/bootstrap.mdx
packages/melos/lib/src/command_runner/bootstrap.dart
packages/melos/lib/src/commands/bootstrap.dart
packages/melos/test/commands/bootstrap_test.dart

Adds the `--offline` flag to the bootstrap command.
Fixes: #714

feat: Expose `pub get`'s `--offline` flag on the bootstrap command

---

packages/melos/lib/src/commands/exec.dart
packages/melos/test/commands/exec_test.dart

This change sets the concurrency to 1 when there are cyclic dependencies and you are running `exec` with `--order-dependents`.
Fixes: #610

fix: Don't deadlock on cycle exec with order dependents

---

packages/melos/lib/src/commands/exec.dart
packages/melos/test/commands/exec_test.dart

When `--fail-fast` is enabled we should propagate the error code.
Fixes: #527

fix: Propagate error code when fail fast is enabled

---

docs/commands/bootstrap.mdx
docs/configuration/overview.mdx
packages/melos/lib/src/command_runner/bootstrap.dart
packages/melos/lib/src/commands/bootstrap.dart
packages/melos/test/commands/bootstrap_test.dart

Adds the possibility to run `--no-enforce-lockfile` in a command to override the melos.yaml settings.
Fixes: #734

feat: Allow overriding `enforceLockfile` with `--no-enforce-lockfile`

---

packages/melos/README.md

replace with a correct melos action link

docs: wrong melos action link

---

melos.yaml.schema.json

This pull request addresses an issue in the official Melos schema configuration for the `melos.yaml` file. Specifically, it adds the missing schema definition for the `steps` field.
The current official schema lacks the definition for the `steps` field in `melos.yaml`. This omission causes validation errors when users attempt to use the `steps` field in their `melos.yaml` files.
Add the `steps` property to the `script` definition in the `$defs.script` section of `melos.yaml.schema.json`.
The changes have been validated in the repository at https://github.com/blendthink/melos-yaml-scheme.

chore: Add the `steps` property

---

bin/melos_dev.dart

The tip is being printed only with `--help`, it should be available with `-h` too.

fix: Prints local development when `-h`

---

packages/melos/lib/src/commands/analyze.dart
packages/melos/test/commands/analyze_test.dart

Current `melos analyze` command is running `dart analyze` instead of `flutter analyze` on flutter projects
https://github.com/invertase/melos/issues/792

fix: Run `flutter analyze` for flutter packages

---

packages/melos/lib/src/common/extensions/dependency.dart
packages/melos/test/commands/bootstrap_test.dart
packages/melos/test/utils.dart

Before this fix (after moving to pubspec_parse), when we updated shared dependencies they would explicitly use the version field.
Example before this PR:
```yaml
dependencies:
flame:
version: ^1.21.0
```
After this PR:
```yaml
dependencies:
flame: ^1.21.0
```

fix: Simple hosted dependencies should be inlined

---

packages/melos/test/commands/analyze_test.dart
packages/melos/test/commands/format_test.dart
packages/melos/test/commands/run_test.dart

Several of the existing test cases failed locally due to inconsistent terminal width logic. This problem surfaced when run on a Mac, using iTerm2 and Bash 5, with a terminal width greater than 80. Some tests, but not all, were hardcoded with output that was 80 wide.
This change makes all the tests consistently use dynamic terminal width in output comparison.
It might be argued that Melos shouldn't write dashed lines longer than 80 anyway, but that's an output design question and beyond the scope of this narrow fix.
Also reinstated two output-checking tests that were skipped since they were sensitive to processing time differences. This was done by simply using regexps for the varying time.
- [ x] 🛠️ `fix` -- Bug fix (non-breaking change which fixes an issue)

fix: Fixed output tests that failed on some terminals

---

packages/melos/lib/src/command_configs/bootstrap.dart
packages/melos/test/commands/bootstrap_test.dart
packages/melos/test/matchers.dart
packages/melos/test/pubspec_extension.dart
packages/melos/test/utils.dart

Fix failing tests due to Flutter upgrade to version 3.27.

fix: failing tests due to Flutter upgrade to version 3.27.

---

packages/melos/lib/src/package.dart
packages/melos/test/matchers.dart

Fixing https://github.com/invertase/melos/issues/803
I was thinking of creating a new Future extension to handle parallelism, but then I discovered that Stream.parallel already does the job by using the number of processors for concurrency. It turned out to be a perfect fit for what I needed

fix: too many open files while creating a workspace

---

packages/melos/lib/src/commands/version.dart

As discussed in Discord I have modified the `_setPubspecVersionForPackage` method to allow for nested versions to be updated.
Context: https://discord.com/channels/295953187817521152/1059839794760392734/1326708821808119870

fix: Fixed versioning for nested version fields

---

packages/melos/lib/src/commands/bootstrap.dart
packages/melos/lib/src/common/extensions/dependency.dart
packages/melos/test/commands/bootstrap_test.dart
packages/melos/test/pubspec_extension.dart
packages/melos/test/test_assets/add_to_app_json.json
packages/melos/test/test_assets/plugin_json.json
packages/melos/test/utils.dart

Fixes comparison check of `GitReference` by also comparing the `path`.
Fixes #658.

fix: fix git dependencies comparison on bootstrap

---

packages/melos/lib/src/commands/bootstrap.dart
packages/melos/lib/src/common/utils.dart
packages/melos/test/commands/clean_test.dart

fix: Replace `\\` with `/` when generating `pubspec_overrides.yaml` on Windows

---

packages/melos/lib/src/common/extensions/dependency.dart

Brings in the v6.3.2 hotfix to v7, it fixes #838.

fix: Properly format Git and HostedDependency

---

packages/melos/lib/src/commands/bootstrap.dart
packages/melos/test/commands/bootstrap_test.dart

feat: Rollback on failed shared dependency resolution

---

CHANGELOG.md
packages/melos/CHANGELOG.md
packages/melos/lib/src/commands/version.dart
packages/melos/lib/version.g.dart
packages/melos/pubspec.yaml

When we swapped to `pubspec_parse` the logic for versioning externally hosted packages was overlooked.
Fixes: #851 
This also reverts the recent versioning of Melos so that it can be included in the new version.

fix: Fix externally hosted versioning

---

packages/melos/lib/src/commands/clean.dart

This PR optimizes the `_cleanPackage` method by precomputing the paths to clean (`pathsToClean`) before iterating through them. Specifically, relative paths are joined with the package root using `p.join` ahead of time, avoiding repeated path computations during the loop.
**Precomputing Paths**:
- `pathsToClean` now contains fully resolved paths created by combining relative paths (`cleanablePubFilePaths` and `.dart_tool`) with the package root.
- This eliminates the need for `p.join` operations inside the loop, improving both performance and code readability.
---
---

refactor: optimize clean command by precomputing paths to clean

---

packages/melos/lib/src/commands/init.dart
packages/melos/test/commands/format_test.dart
packages/melos/test/commands/init_test.dart

`melos init` currently adds an empty string to `melos:` and an empty list/array to `workspace:` in pubsspec.yaml when generating it. This is a limitation of the yaml package we're using. A workaround to remove these has been implemented

fix: Melos init adding empty string / list in pubspec.yaml

---

docs/configuration/overview.mdx
packages/melos/lib/src/common/intellij_project.dart
packages/melos/lib/src/workspace_config.dart
packages/melos/templates/intellij/runConfigurations/shell_script.xml.tmpl
packages/melos/test/workspace_config_test.dart

This PR aims to add support for `executeInTerminal` for IntelliJ run configurations allowing scripts to be ran in the "Run" panel instead of the terminal

feat: Add support for executeInTerminal for IntelliJ run configs

---

docs/index.mdx
packages/melos/README.md

https://github.com/ReactiveX/rxdart
- add ReactiveX/rxdart to README

docs: add ReactiveX/rxdart to README and docs

---

docs/index.mdx
packages/melos/README.md

Add Stac to the list of projects using Melos.

docs: Add Stac to the list of projects using Melos.

---

docs/configuration/scripts.mdx
packages/melos/lib/src/command_runner.dart
packages/melos/test/command_runner_test.dart

Fixes https://github.com/invertase/melos/issues/874.
This PR makes it so that if you have a custom script defined in `pubspec.yaml` that has the same name as a built-in command (e.g. `format`), that script will be run when you invoke _either_ `melos <script>` or `melos run <script>`. Before this change, your script would NOT be run if you ran `melos <script>`, the built-in command would be run, which is not expected.
**One important behavioral quirk I noticed when making this change:** Custom scripts are not included in `--help` invocation. This is because:
- An empty workspace is used when `--help` is passed.
- Custom scripts are hidden via `ScriptCommand` having `hidden` set to `true`
I found this behavior to be unexpected. I was able to make custom scripts show up in `--help` by …

feat(scripts): allow overriding default scripts with custom ones

---

docs/getting-started.mdx

Globs in the workspace definition will be supported from Dart 3.11, so a note regarding that is added.

docs: Add note about globs support from Dart 3.11
